TrajectoryPlannerROS:
  acc_lim_x: 0.1
  acc_lim_y: 0.1
  acc_lim_theta: 0.8

  max_vel_x: 0.6
  min_vel_x: 0.1

  max_vel_theta: 2.0
  min_vel_theta: -2.0

  min_in_place_vel_theta: 1.5

  backup_vel: -0.1
  escape_vel: -0.1

  holonomic_robot: false

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.5


  # meter_scoring: true
  pdist_scale: 1.8
  gdist_scale: 2.5

  # dwa: false
  # occdist_scale: 0.001
  # heading_lookahead: 2.5
  # heading_scoring: true

  # x_samples: 20
  # theta_samples: 40

  # sim_time: 3.0
